import { Inter } from "next/font/google";
import "./globals.css";
import Header from './../components/header/Header';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import {Providers} from "./providers";
import Footer from "@/components/footer/Footer";

export default function RootLayout({children}) {
  return (
    <html lang="en" className='dark'>
      <body>
        <Providers>
          <Header/>
          {children}
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}
