import { Philosopher, Roboto } from "next/font/google";
import "./globals.css";

const philosopher_init = Philosopher({
  subsets:['latin'],
  weight: ['400','700'],
  variable: '--font-philosopher',
})

const roboto_init = Roboto({
  subsets:['latin'],
  weight: ['300','400','700'],
  variable: '--font-roboto',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${philosopher_init.variable} ${roboto_init.variable}`}>{children}</body>
    </html>
  );
}
