import { Philosopher, Roboto, Montserrat, Bentham } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import { Providers } from "./providers";
import { GoogleAnalytics } from '@next/third-parties/google'

const philosopher_init = Philosopher({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-philosopher',
})

const roboto_init = Roboto({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
  variable: '--font-roboto',
});

const bentham_init = Bentham({
  subsets: ['latin'],
  weight: ["400"],
  variable: '--font-bentham',
});

const montserrat_init = Montserrat({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
  variable: '--font-montserrat',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='light'>
      <body className={`${philosopher_init.variable} ${roboto_init.variable} ${montserrat_init.variable} ${bentham_init.variable}`}>
        <Header />
        <Providers>
          {children}
        </Providers>
      </body>
      <GoogleAnalytics gaId={`${process.env.NEXT_PUBLIC_GID}`} />
    </html>
  );
}
